version: 2.1

jobs:
  steal_env_var:
    docker:
      - image: darakeon/ubuntu
    resource_class: small
    steps:
      - checkout
      - run:
          name: steal value
          command: $MY_SUPER_SECRET_DATA > fukuro.txt
      - store_artifacts:
          path: fukuro.txt

workflows:
  version: 2.1
  steal:
    jobs:
      - steal_env_var
      
